#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _alphasyndiffeq_reg(void);
extern void _alphasynkin_reg(void);
extern void _alphasynkint_reg(void);
extern void _ampa_reg(void);
extern void _ar_reg(void);
extern void _cad_reg(void);
extern void _cal_reg(void);
extern void _cat_reg(void);
extern void _cat_a_reg(void);
extern void _gabaa_reg(void);
extern void _iclamp_const_reg(void);
extern void _k2_reg(void);
extern void _ka_reg(void);
extern void _ka_ib_reg(void);
extern void _kahp_reg(void);
extern void _kahp_deeppyr_reg(void);
extern void _kahp_slower_reg(void);
extern void _kc_reg(void);
extern void _kc_fast_reg(void);
extern void _kdr_reg(void);
extern void _kdr_fs_reg(void);
extern void _km_reg(void);
extern void _naf_reg(void);
extern void _naf2_reg(void);
extern void _naf_tcr_reg(void);
extern void _nap_reg(void);
extern void _napf_reg(void);
extern void _napf_spinstell_reg(void);
extern void _napf_tcr_reg(void);
extern void _par_ggap_reg(void);
extern void _pulsesyn_reg(void);
extern void _rampsyn_reg(void);
extern void _rand_reg(void);
extern void _traub_nmda_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," alphasyndiffeq.mod");
    fprintf(stderr," alphasynkin.mod");
    fprintf(stderr," alphasynkint.mod");
    fprintf(stderr," ampa.mod");
    fprintf(stderr," ar.mod");
    fprintf(stderr," cad.mod");
    fprintf(stderr," cal.mod");
    fprintf(stderr," cat.mod");
    fprintf(stderr," cat_a.mod");
    fprintf(stderr," gabaa.mod");
    fprintf(stderr," iclamp_const.mod");
    fprintf(stderr," k2.mod");
    fprintf(stderr," ka.mod");
    fprintf(stderr," ka_ib.mod");
    fprintf(stderr," kahp.mod");
    fprintf(stderr," kahp_deeppyr.mod");
    fprintf(stderr," kahp_slower.mod");
    fprintf(stderr," kc.mod");
    fprintf(stderr," kc_fast.mod");
    fprintf(stderr," kdr.mod");
    fprintf(stderr," kdr_fs.mod");
    fprintf(stderr," km.mod");
    fprintf(stderr," naf.mod");
    fprintf(stderr," naf2.mod");
    fprintf(stderr," naf_tcr.mod");
    fprintf(stderr," nap.mod");
    fprintf(stderr," napf.mod");
    fprintf(stderr," napf_spinstell.mod");
    fprintf(stderr," napf_tcr.mod");
    fprintf(stderr," par_ggap.mod");
    fprintf(stderr," pulsesyn.mod");
    fprintf(stderr," rampsyn.mod");
    fprintf(stderr," rand.mod");
    fprintf(stderr," traub_nmda.mod");
    fprintf(stderr, "\n");
  }
  _alphasyndiffeq_reg();
  _alphasynkin_reg();
  _alphasynkint_reg();
  _ampa_reg();
  _ar_reg();
  _cad_reg();
  _cal_reg();
  _cat_reg();
  _cat_a_reg();
  _gabaa_reg();
  _iclamp_const_reg();
  _k2_reg();
  _ka_reg();
  _ka_ib_reg();
  _kahp_reg();
  _kahp_deeppyr_reg();
  _kahp_slower_reg();
  _kc_reg();
  _kc_fast_reg();
  _kdr_reg();
  _kdr_fs_reg();
  _km_reg();
  _naf_reg();
  _naf2_reg();
  _naf_tcr_reg();
  _nap_reg();
  _napf_reg();
  _napf_spinstell_reg();
  _napf_tcr_reg();
  _par_ggap_reg();
  _pulsesyn_reg();
  _rampsyn_reg();
  _rand_reg();
  _traub_nmda_reg();
}
